name: Examenis Build Node Server
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy Environment: [prod]'
        required: true
        default: 'prod'

jobs:
  build:
    environment:
      name: ${{ github.event.inputs.environment || 'prod' }}
    env:
      sshKey: ${{ secrets.EDO_JENKINS }}
      repository: ${{ secrets.EXAMENIS_REPO_NODE_SERVER }}
    name: Build image
    runs-on: [ self-hosted, edo ]
    steps:
      - name: prepare keys
        run: |
          echo "hello world"
          echo $sshKey > private_key_file
      - name: checkout source code
        run: |
          ssh -i private_key_file -o IdentitiesOnly=yes' 
          git clone $repository
      - name: checkout source code
        run: |
          ls
          
