name: Examenis Build Node Server
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy Environment: [prod]'
        required: true
        default: 'prod'

jobs:
  build:
    environment:
      name: ${{ github.event.inputs.environment || 'prod' }}
    env:
      repository: ${{ secrets.EXAMENIS_REPO_NODE_SERVER }}
      repositoryParticipantClient: ${{ secrets.EXAMENIS_REPO_CLIENT_PARTICIPANT }}
      sshkey: ${{ secrets.SSH_KEY }}
      sshpwd: ${{ secrets.SSH_PWD }}
      KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
    name: Build image
    runs-on: [ self-hosted ]
    steps:
      - name: install xclip
        continue-on-error: true
        run: |
          yum install xclip
      - name: prepare hello world
        continue-on-error: true
        run: |
          echo "$sshkey" > edoJenkins.ppk
          ls -rtl
          more edoJenkins.ppk
          chmod 600 edoJenkins.ppk
          eval `ssh-agent -s`
          echo "hello world"
          rm -rf examenisClientParticipant
          rm -rf examenisnode
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.sshkey }}
          name: id_rsa # optional
          known_hosts: ${{ env.KNOWN_HOSTS }}
          config: |
            StrictHostKeyChecking no
          if_key_exists: replace # replace / ignore / fail; optional (defaults to fail)
      - name: checkout source code of examenis participant client
        # GIT_SSH_COMMAND='ssh -i edoJenkins.ppk -o IdentitiesOnly=yes' git clone $repositoryParticipantClient
        run: |
          git clone $repositoryParticipantClient
      - name: checkout source code
        run: |
          git clone $repository
      - uses: actions/setup-node@v1
        continue-on-error: true
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: create participant client
        run: |
          ls
          cd examenisClientParticipant
          ls
          pwd
          chmod +x createProdCI.sh
          ./createProdCI.sh
      - name: create participant node server docker
        run: |
          pwd
          cd examenisnode
          chmod +x createDocker.sh
          ./createDocker.sh
        shell: bash
      - name: cleanup
        run: |
          rm -rf examenisnode
          
