name: Examenis Build Node Server
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy Environment: [prod]'
        required: true
        default: 'prod'

jobs:
  build:
    environment:
      name: ${{ github.event.inputs.environment || 'prod' }}
    env:
      repository: ${{ secrets.EXAMENIS_REPO_NODE_SERVER }}
      repositoryParticipantClient: ${{ secrets.EXAMENIS_REPO_CLIENT_PARTICIPANT }}
    name: Build image
    runs-on: [ self-hosted, edo ]
    steps:
      - name: prepare hello world
        continue-on-error: true
        run: |
          echo "hello world"
          rm -rf examenisClientParticipant
          rm -rf examenisnode
      - name: checkout source code of examenis participant client
        run: |
          GIT_SSH_COMMAND='ssh -i /home/ghrunner/edoJenkins.ppk -o IdentitiesOnly=yes' git clone $repositoryParticipantClient
      - name: checkout source code
        run: |
          GIT_SSH_COMMAND='ssh -i /home/ghrunner/edoJenkins.ppk -o IdentitiesOnly=yes' git clone $repository
      - name: create participant client
        run: |
          ls
          cd examenisClientParticipant
          ls
          pwd
          chmod +x createProdCI.sh
          ./createProdCI.sh
      - name: create participant node server docker
        run: |
          pwd
          cd examenisnode
          chmod +x createDocker.sh
          ./createDocker.sh
        shell: bash
      - name: cleanup
        run: |
          rm -rf examenisnode
          
