name: Nightly Backup

on:
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run backup script
        env:
          BACKUP_PATH: ${{ secrets.BACKUP_PATH }}
        run: |
          cd $BACKUP_PATH
          bash doBackup.sh 

      - name: Remove old files
        env:
          BACKUP_PATH: ${{ secrets.BACKUP_PATH }}
        run: |
          cd $BACKUP_PATH/old
          find . -type f -mtime +7 -exec rm {} \;
